exoplanet-dev/jaxoplanet

- src/exo4jax/_src/keplerian.py
- src/exo4jax/_src/light_curves.py
- src/exo4jax/_src/proto.py
- src/exo4jax/_src/transit.py
- src/exo4jax/_src/types.py
- src/exo4jax/test_utils.py
- tests/keplerian_test.py
- tests/light_curves_test.py
- tests/orbits_test.py
This fixes the issues with `vmap` dimensions and `dtype`s reported by @catrionamurray in #2 and #3.
There are some questions about how to best define the interface for multi-planet systems. Right now, the `light_curve` function explicitly handles this:
https://github.com/exoplanet-dev/exo4jax/blob/49169bf117d71f92ab633771a928c4543d7d41a3/src/exo4jax/_src/light_curves.py#L88-L93
But that feels a bit brittle.
We should also port these fixes to the `TransitOrbit` since we'll have the same issues there.
Closes #2 
Closes #3
> Fixing #2 and #3

- .github/workflows/tests.yml
In some of the PRs from the docathon (#107, #108, #109, #110, and #111 lol) we're getting build errors on the Read the Docs that are hard to debug. This PR adds a workflow on GitHub Actions that should build the docs in nearly the same environment as on RTDs, and then upload the full build output if it fails. This should make it easier to track down the issues.
> Upload docs build logs when the build fails

- pyproject.toml
The previous setup was emitting the following warning:
```
warning: The top-level linter settings are deprecated in favour of their
counterparts in the `lint` section. Please update the following options
in `pyproject.toml`:
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'isort' -> 'lint.isort'
```
> Updating ruff configuration

- .gitignore
- src/jaxoplanet/orbits/keplerian.py
- tests/orbits/keplerian_test.py
The `_body_stack` is an implementation detail that we don't really need most users to think about. Since we're now encourage users to print these objects to inspect them, I wanted to de-emphasize this field. With this in mind, this PR updates the `__repr__` in `System` to "truncate" this field. This means that we now see something like:
```python
>>> System().add_body(period=1)
System(
central=Central(
mass=<Quantity(1.0, 'M_sun')>,
radius=<Quantity(1.0, 'R_sun')>,
density=<Quantity(0.238732415, 'M_sun / R_sun ** 3')>
),
bodies=(
Body(
central=Central(
mass=<Quantity(1.0, 'M_sun')>,
radius=<Quantity(1.0, 'R_sun')>,
density=<Quantity(0.238732415, 'M_sun / R_sun ** 3')>
),
time_ref=<Quantity(-0.25, 'day')>,
time_transit=<Quantity(0, 'day')>,
period=<Quantity(1, 'day')>, …
```
> Truncate `_body_stack` in Keplerian `System`'s `__repr__`

- docs/tutorials/transit.ipynb
I'm not sure that we'd want to merge this, but I've sketched out some ideas that make the transit fitting example a bit faster to run. One extra point here is that I'm also not getting any divergences anymore, so we can factor that part out of this tutorial (perhaps we could talk about it in the "intro to numpyro" tutorial?). The only real changes that I made were to:
1. Reduce parallelism (RTDs definitely doesn't allocate 4 cores)
2. Reduce size of dataset smaller and choose somewhat easier parameters
What do you think, @soichiro-hattori?
> Drafting faster transit fitting tutorial

- src/jaxoplanet/object_stack.py
- src/jaxoplanet/orbits/keplerian.py
- tests/object_stack_test.py
- tests/orbits/keplerian_test.py
As part of #134, I wanted to move the body stack logic to a separate object. This means that we can reuse the same logic for a stack of "maps" without reimplementing it.
> Factoring the "body stack" logic out to a generic "object stack"

- docs/tutorials/transit.ipynb
- src/jaxoplanet/core/limb_dark.py
- src/jaxoplanet/exposure_time.py
- src/jaxoplanet/light_curves.py
- tests/light_curves_test.py
@soichiro-hattori — Check this out! I think this is potentially cool, and might simplify some of our logic around light curve models. Basically the idea is that we can factor the exposure time integration out of the `LightCurve` object into a function transformation. This is a bit more "JAX-y" and means that we could support different kinds of light curve models more easily. The use would look something like:
```python
import jax
import jax.numpy as jnp
from jaxoplanet.orbits import keplerian
from jaxoplanet.light_curves import LimbDarkLightCurve
from jaxoplanet.exposure_time import integrate_exposure_time
central = keplerian.Central(mass=5, radius=2)
system = keplerian.System(central).add_body(radius=0.05, period=3.0)
def light_curve(time):
return LimbDarkLightCurve().light_curve(system, …
```
> Experimenting with a different interface for exposure time

- .zenodo.json
In https://github.com/exoplanet-dev/jaxoplanet/pull/87 we forgot to add @shashankdholakia to `.zenodo.json`. This fixes that.
@shashankdholakia: can you check that all the info that I added is right?
> Adding @shashankdholakia to zenodo.json

- pyproject.toml
- src/jaxoplanet/experimental/starry/light_curves.py
- src/jaxoplanet/experimental/starry/maps.py
It doesn't really make sense to have a default period of 10^15, when we could instead just handle the case of no rotation using a condition. I fixed that and a few tiny typing issues. Take a look, @lgrcia!
> Fixing type annotations for starry Map and removing default period

- src/jaxoplanet/experimental/starry/maps.py
- src/jaxoplanet/experimental/starry/ylm.py
This PR fixes some minor bugs and docs issues in the starry module.
1. Update doc for `inc` argument in `Map` class to mention that it's initialized at 90 degrees (not 0) and that the angle is measured relative to the line of sight.
2. Add `self.normalize=normalize` in `Map` initialization so that it's string representation isn't `None`.
3. Fix doc mentions of `relative` in `Ylm` since we call it `normalize`.
4. In `Map` initialization, when in `normalize=True` block, cast `y[(0,0)]` to `float` as it's otherwise a JAX `ArrayImpl` that doesn't show the value in the string representation.
> Minor starry fixes

- pyproject.toml
The numpyro compatibility issue was fixed in https://github.com/dfm/numpyro-ext/pull/32 by @vandalt. 
Fixes #160
> Remove numpyro version bound

- src/jaxoplanet/experimental/starry/rotation.py
- src/jaxoplanet/experimental/starry/surface.py
- tests/experimental/starry/rotation_test.py
Faster rotations of the spherical harmonics. This is described in the technical paper but the idea is to go from 6 rotations
to 4
In the previous implementation [I merged all rotations](#83), which ends up not being optimal (because of the rotation around y).
The combined rotation to orient the star in the plane of the sky is defined by the axis
```math
\begin{equation}
v = \frac{1}{\sqrt{1 - \cos^2{\left(\frac{inc}{2} \right)} \cos^2{\left(\frac{obl}{2}\right)}}} \begin{pmatrix}
\sin{\left(\frac{inc}{2} \right)} \cos{\left(\frac{obl}{2}\right)}\\
\sin{\left(\frac{inc}{2} \right)} \sin{\left(\frac{obl}{2}\right)}\\
- \cos{\left(\frac{inc}{2} \right)} \sin{\left(\frac{obl}{2}\right)}\\
\end{pmatrix},
\end{equation}
```
and angle $\omega = 2 \cos^{-1}{\left(\cos{\left(\frac{inc}{2} \right)} …
> feat: faster rotation decomposition + refactor axis angle functions

- src/jaxoplanet/experimental/starry/light_curves.py
- src/jaxoplanet/experimental/starry/surface.py
- src/jaxoplanet/experimental/starry/utils.py
- src/jaxoplanet/object_stack.py
- tests/experimental/starry/light_curve_test.py
This PR fixes the computation of the starry light curves, given that the body surfaces have different amplitudes. It also introduces tests using a simple system of eclipsing binaries, verifying the magnitude of the light curve at certain points in the orbit (e.g. all conjunctions) and make sure that interchanging the primary and secondary (plus a shift in phase) leads to the same light curves (thanks @soichiro-hattori for the suggestion!).
It also adds the possibility to set the rotation phase of a surface map.
> feat: amplitude surface light curves for starry systems + tests

- docs/index.md
I think the landing page is hard to parse otherwise...
Edited to add the rendered link: https://jaxoplanet--198.org.readthedocs.build/en/198/
> Add maxdepth argument to toctrees in docs

- pyproject.toml
- src/jaxoplanet/light_curves/emission.py
- tests/experimental/starry/light_curve_test.py
A light_curve function taking into account transit and occultations of emissive (optionally limb darkened) bodies.
This function takes a `SurfaceSystem` in so that the limb darkening and amplitude of each body is defined using the `Surface` object.
Example:
```python
import jax.numpy as jnp
import matplotlib.pyplot as plt
from jaxoplanet.orbits import keplerian
from jaxoplanet.experimental.starry.surface import Surface
from jaxoplanet.experimental.starry.orbit import SurfaceSystem
from jaxoplanet.light_curves.emission import light_curve
central = keplerian.Central()
system = SurfaceSystem(central, Surface(u=(0.1, 0.2), amplitude=1.0)).add_body(
radius=0.5, period=1.0, surface=Surface(amplitude=0.5, normalize=False)
)
period = system.bodies[0].period.magnitude
time = jnp.linspace(-0.8 * …
```
> feat: secondary/emission light curve of (limb-darkened) bodies

- src/jaxoplanet/orbits/keplerian.py
Seems like there was an unpacking bug in relative angles
> Fixed relative angles unpacking bug

- .github/workflows/tests.yml
Comparison tests failed potentially due to https://github.com/actions/runner-images/issues/10636. Fixing by downgrading ubuntu-latest to ubuntu-22.04. Thanks @lgarrison 🙏🏼
> fix: attempt for comparison test ci

- src/jaxoplanet/starry/light_curves.py
- src/jaxoplanet/starry/system_observable.py
- tests/starry/light_curve_test.py
This PR fixes #268. The issue seemed to stem from a code block in the `starry/light_curves.py/surface_light_curve` function for when `surface.ydeg = 0`. In this case the function returned the flux without multiplying it by the `surface.amplitude` value:
https://github.com/exoplanet-dev/jaxoplanet/blob/a3d1b8ce1fb364cc2c30eb2b2c414126695497f9/src/jaxoplanet/starry/light_curves.py#L94
I've changed the above line to
```python
return surface.amplitude * (1.0 + jnp.where(b_occ, lc, 0))
```
and now the `test_EB` test should pass.
> Fix/issue #268

- pyproject.toml
Removing since we no longer depend on `jpu` (and it's github repo)
> remove hatch allow-direct-references=true

- src/jaxoplanet/__init__.py
- src/jaxoplanet/starry/__init__.py
This PR exposes the `starry` and the `starry.light_curves` submodules to fix #280.
The following should now work:
```python
import jaxoplanet as jxo
jxo.starry.light_curves.surface_light_curve()
```
> Expose starry and starry.light_curves submodules to fix #280
